import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import StyledComponentsRegistry from '@/lib/registry';
import Header from '@/common/components/layout/Header';
import ThemeProvider from '@/common/theme/ThemeProvider';

const geistSans = localFont({
  src: '../common/fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '../common/fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StyledComponentsRegistry>
          <ThemeProvider>
            <Header />
            <div>{children}</div>
          </ThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
